insert into validator values(1,'com.operalot.validator.game1.ValidatorFacade','com.operalot.validator.facade.game1.ValidatorIncomingFacade','Validator Game1','com.operalot.validator.facade.game1.ValidatorOutgoingFacade',NULL);
insert into game values(1,'game1', 1);
update validator set GAMEENTITY_ID = 1 where id = 1;
insert into validator values(2,'com.operalot.validator.game1.ValidatorFacade','com.operalot.validator.facade.game2.ValidatorIncomingFacade','Validator Game2','com.operalot.validator.facade.game2.ValidatorOutgoingFacade',NULL);
insert into game values(2,'game2', 2);
update validator set GAMEENTITY_ID = 2 where id = 2;
insert into field values (1, 'field1.game1', 'Field 1 - Game 1'   , 'field1');
insert into field values (2, 'field2.game1', 'Field 2 - Game 1'   , 'field2');
insert into field values (3, 'field3.game1', 'Field 3 - Game 1'   , 'field3');
insert into field values (4, 'field4.game1', 'Field 4 - Game 1'   , 'field4');
insert into field values (5, 'field5.game1', 'Field 5 - Game 1'   , 'field5');
insert into field values (6, 'field6.game1', 'Field 6 - Game 1'   , 'field6');
insert into field values (7, 'field7.game1', 'Field 7 - Game 1'   , 'field7');
insert into field values (8, 'field8.game1', 'Field 8 - Game 1'   , 'field8');
insert into field values (9, 'field9.game1', 'Field 9 - Game 1'   , 'field9');
insert into field values (10, 'field10.game1', 'Field 10 - Game 1', 'field10');
insert into field values (11, 'field1.game2', 'Field 1 - Game 2'  , 'field1');
insert into field values (12, 'field2.game2', 'Field 2 - Game 2'  , 'field2');
insert into field values (13, 'field3.game2', 'Field 3 - Game 2'  , 'field3');
insert into field values (14, 'field4.game2', 'Field 4 - Game 2'  , 'field4');
insert into validator_field values(1, 1);
insert into validator_field values(1, 2);
insert into validator_field values(1, 3);
insert into validator_field values(1, 4);
insert into validator_field values(1, 5);
insert into validator_field values(1, 6);
insert into validator_field values(1, 7);
insert into validator_field values(1, 8);
insert into validator_field values(1, 9);
insert into validator_field values(1, 10);
insert into validator_field values(2, 11);
insert into validator_field values(2, 12);
insert into validator_field values(2, 13);
insert into validator_field values(2, 14);

